-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- vim.cmd([[
-- 	augroup ColorSchemeOverride
-- 	au!
-- 	au ColorScheme *
-- 		highlight! TelescopeTitle cterm=NONE gui=NONE ctermbg=Darkgray guibg=NONE guifg=#FF0000
-- ]])
-- vim.api.nvim_exec_autocmds("ColorScheme", {})
